SFA-2: Create Student-Questions-Model
HocVienCongGiao/portal-frontend-ngx pull request #16
Opened 2021-05-20 14:03 UTC by xuantruongcox

### Please read and mark the following check list before creating a pull request (check one with "x"):

 - [ ] I read and followed the [CONTRIBUTING.md](https://github.com/akveo/ngx-admin/blob/master/CONTRIBUTING.md) guide.
 - [ ] I read and followed the [New Feature Checklist](https://github.com/akveo/ngx-admin/blob/master/DEV_DOCS.md#new-feature-checklist) guide.
 
 #### Short description of what this resolves:

2021-05-21 15:09 UTC, ProjectHocVienCongGiao requested changes
The test is failing

2021-05-21 15:09 UTC, ProjectHocVienCongGiao commented on src/app/@core/models/question-controls/question-dropdown.ts
> +export class DropdownQuestion extends QuestionBase<string>{
This should be renamed to BaseQuestion

2021-05-21 15:09 UTC, ProjectHocVienCongGiao commented on src/app/guest-pages/guest-pages.component.ts
> +export class GuestPagesComponent {
what does this component do?

2021-05-22 14:51 UTC, xuantruongcox commented on src/app/guest-pages/guest-pages.component.ts
> +export class GuestPagesComponent {
sorry sir, this's layout for guest

2021-05-24 01:49 UTC, ProjectHocVienCongGiao commented on src/app/@core/mock/question-control.service.ts
> +import { BaseQuestion } from '../models/question-student';
```suggestion
import { BaseQuestion } from '../models/student-question';
```

2021-05-24 01:51 UTC, ProjectHocVienCongGiao reviewed
Some grammar mistake

2021-06-04 16:41 UTC, nguyenhongphat0 approved these changes

2021-06-04 16:42 UTC, nguyenhongphat0 approved these changes

2021-06-04 16:43 UTC, nguyenhongphat0 approved these changes

2021-06-04 16:44 UTC, merged