Integrate amplify and auth
HocVienCongGiao/portal-frontend-ngx pull request #2
Opened 2021-04-24 05:01 UTC by nguyenhongphat0

- [x] Integrate amplify
 - [x] Amplify add auth
 - [x] Login/Logout and navigation flow

2021-04-26 16:59 UTC, peterbean410 requested changes
Plural -> singular at some places
1. UsersModule -> UserModule
2. UsersComponent -> UserListComponent
3. Users Management -> User Management
4. UsersRoutingModule -> UserRoutingModule
5. users.component.ts -> user-list.component.ts

And also look at my other comments, pleaseeee.

2021-04-26 16:59 UTC, peterbean410 commented on src/app/app.module.ts
> +});
Let's not hard code config parameters here, instead put them in variable environments.

2021-04-26 16:59 UTC, peterbean410 commented on e2e/src/app.po.ts
> +  }
I would put these in `auth.po.ts` file

2021-04-26 16:59 UTC, peterbean410 commented on e2e/src/app.e2e-spec.ts
>    });
We are testing AUTH flow here, so let's put them under `auth.e2e-spec.ts`

2021-04-26 16:59 UTC, peterbean410 commented on .gitignore
> +amplify/backend/.temp
how about `amplify/` ? We want to ignore all amplify related config, don't we?

2021-04-26 16:59 UTC, peterbean410 commented on package.json
> +    "protractor": "protractor",
Can you explain why we need this?

2021-04-26 16:59 UTC, peterbean410 commented on e2e/src/app.e2e-spec.ts
> +    expect(await page.getTitleText()).toEqual('Users Management');
```suggestion
    expect(await page.getTitleText()).toEqual('User Management');
```

2021-04-26 16:59 UTC, peterbean410 commented on src/app/pages/pages-routing.module.ts
> +        .then(m => m.UsersModule),
Should change all UsersModule to the singular form UserModule

2021-04-26 16:59 UTC, peterbean410 commented on src/app/pages/pages.module.ts
> +    UsersModule,
Please ask me about the noun to use before you start putting the name to the code. Should be UserModule

2021-04-26 16:59 UTC, peterbean410 commented on src/app/pages/users/users.component.ts
> +    this.titleService.setTitle('Users Management');
```suggestion
    this.titleService.setTitle('User Management');
```

2021-04-26 16:59 UTC, peterbean410 commented on src/app/pages/users/users.module.ts
> +    UsersRoutingModule,
```suggestion
    UserRoutingModule,
```

2021-04-26 16:59 UTC, peterbean410 commented on src/app/pages/users/users.module.ts
> +export class UsersModule { }
```suggestion
export class UserModule { }
```

2021-04-26 16:59 UTC, peterbean410 commented on src/app/pages/users/users-routing.module.ts
> +  UsersComponent,
```suggestion
  UserListComponent,
```

2021-04-26 17:44 UTC, nguyenhongphat0 commented on package.json
> +    "protractor": "protractor",
`npm run e2e` first compile the source code and start a dev server before execute e2e test, and it's very slow. If we already have a dev server running (by using `npm start`), `npm run protractor` will execute the e2e test right a way. It's save lots of times when developing e2e test, boss 😫

2021-04-28 13:33 UTC, merged

2021-04-28 14:06 UTC, nguyenhongphat0 commented
Woohoo 🥳